# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-06 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_Detail_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Class_Detail_Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From_Date', models.DateField()),
                ('To_Date', models.DateField()),
                ('courseName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apps.Class_Detail_Course')),
            ],
        ),
    ]
