# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-07 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0002_class_detail_course_class_detail_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.TextField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apps.HomeModel')),
            ],
        ),
        migrations.RemoveField(
            model_name='class_detail_date',
            name='courseName',
        ),
        migrations.DeleteModel(
            name='Class_Detail_Course',
        ),
        migrations.DeleteModel(
            name='Class_Detail_Date',
        ),
    ]
