# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-07 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0003_auto_20190207_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Comment',
            new_name='Comments',
        ),
    ]
