# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-07 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0004_auto_20190207_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homemodel',
            name='id',
        ),
        migrations.AddField(
            model_name='homemodel',
            name='Reg_No',
            field=models.IntegerField(default=1000, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
