# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-07 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0005_auto_20190207_1615'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='CommentModel',
        ),
        migrations.AddField(
            model_name='homemodel',
            name='User_Id',
            field=models.IntegerField(default=1212),
            preserve_default=False,
        ),
    ]
