# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-08 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0006_auto_20190207_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homemodel',
            name='Date',
            field=models.DateField(default=False),
        ),
        migrations.AlterField(
            model_name='homemodel',
            name='Time',
            field=models.TimeField(default=False),
        ),
    ]
