# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-08 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0007_auto_20190208_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homemodel',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='homemodel',
            name='Time',
            field=models.TimeField(),
        ),
    ]
