# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-12 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0008_auto_20190208_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homemodel',
            name='Course_Opted',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='Course_Opted',
            field=models.CharField(default=1212, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homemodel',
            name='Password',
            field=models.CharField(default=22333, max_length=10),
            preserve_default=False,
        ),
    ]
